### ISSUE TITLE
Format of Data File

### ISSUE THREAD

**Issue by hussainjagirdar** [soskek/SDCGAN#1]
What are the actual format of all the pickle files? Can you please share the link to the data set for which this code has been made?

**Comment by soskek** [comment]
Thank you for being interested in this!
This script might be written when I was a student, 2016.  I might lose some related codebase and the pickle files. Even I cannot reproduce the result in README.

I tried to update the model this week with a dataset and the word embedding from a pretrained language model on the corpus, but it does not work yet. But, anyway, I pushed the branch. You can use it, although modification is still required.
https://github.com/soskek/SDCGAN/tree/update-but-does-not-work

**Comment by wiemMH** [comment]
thank you for your job! it helps me. 
I used the DCGAN.py which is in this repo: https://github.com/soskek/SDCGAN/tree/update-but-does-not-work. Although, i have 2 questions: 
- which is the difference between data_file = "coco/dataset.json" and vocab_file_out = "vocab.json" (what should contain each file)
- Why do you use json format? 
thanks :)

**Comment by soskek** [comment]
This repo is dirty and, to be honest, I do NOT recommend using it :)
You may have to use another codebase or implement from scratch!

Anyway, last answers:

https://github.com/soskek/SDCGAN/blob/update-but-does-not-work/DCGAN.py#L109-L123
`data_file` is a dataset file. It contains text sentences. You can use other files if changing these lines.
`vocabl_file_out` is a path for "saving" vocabulary.

I might just love json due to simplicity :), while don't remember.
